# Set the database connection URL
spring.datasource.url=jdbc:postgresql://localhost:5432/garage

# Set the database username and password
spring.datasource.username=postgres
spring.datasource.password=wachtwoord

# Specify the PostgresSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver


# Specify the Hibernate dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Show SQL statements in the console for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Automatically create and drop database schema at startup
spring.jpa.hibernate.ddl-auto=create


# Ensure that SQL scripts are executed on startup
spring.sql.init.mode=always

# Defer data source initialization until all beans are created
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.security=DEBUG
